# Generated by Django 5.1.3 on 2024-11-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_image',
            field=models.ImageField(upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challenge_image',
            field=models.ImageField(upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='counter_image',
            field=models.ImageField(upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_image',
            field=models.ImageField(upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='partner_logo',
            field=models.ImageField(upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_image',
            field=models.ImageField(upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_image',
            field=models.ImageField(upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_image',
            field=models.ImageField(upload_to='upload/'),
        ),
        migrations.AlterField(
            model_name='why_choose_us',
            name='wcu_image',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
