# Generated by Django 5.1.3 on 2024-11-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0004_delete_about_delete_blog_delete_challenge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_heading', models.CharField(max_length=250)),
                ('about_details', models.TextField()),
                ('about_image', models.ImageField(upload_to='static/')),
                ('about_point_1_title', models.CharField(max_length=250)),
                ('about_point_1_details', models.TextField()),
                ('about_point_2_title', models.CharField(max_length=250)),
                ('about_point_2_details', models.TextField()),
                ('about_point_3_title', models.CharField(max_length=250)),
                ('about_point_3_details', models.TextField()),
                ('about_point_4_title', models.CharField(max_length=250)),
                ('about_point_4_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefits_title', models.CharField(max_length=100)),
                ('benefits_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challege_title', models.CharField(max_length=250)),
                ('challenge_image', models.ImageField(upload_to='static/')),
                ('challenge_1_title', models.CharField(max_length=250)),
                ('challenge_1_details', models.TextField()),
                ('challenge_2_title', models.CharField(max_length=250)),
                ('challenge_2_details', models.TextField()),
                ('challenge_3_title', models.CharField(max_length=250)),
                ('challenge_3_details', models.TextField()),
                ('challenge_4_title', models.CharField(max_length=250)),
                ('challenge_4_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=250)),
                ('user_phone_number', models.IntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('user_msg_subject', models.CharField(max_length=250)),
                ('user_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_heading', models.CharField(max_length=45)),
                ('counter_details', models.TextField()),
                ('counter_image', models.ImageField(upload_to='static/')),
                ('count_1_title', models.CharField(max_length=250)),
                ('count_1_value', models.CharField(max_length=250)),
                ('count_2_title', models.CharField(max_length=250)),
                ('count_2_value', models.CharField(max_length=250)),
                ('count_3_title', models.CharField(max_length=250)),
                ('count_3_value', models.CharField(max_length=250)),
                ('count_4_title', models.CharField(max_length=250)),
                ('count_4_value', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_image', models.ImageField(upload_to='static/')),
                ('feature_title', models.CharField(max_length=250)),
                ('feature_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Heading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_small_title', models.CharField(max_length=10)),
                ('heading_title', models.CharField(max_length=15)),
                ('heading_details', models.TextField()),
                ('heading_image', models.ImageField(upload_to='static/')),
                ('heading_video', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members_image', models.ImageField(upload_to='static/')),
                ('members_name', models.CharField(max_length=250)),
                ('members_post', models.CharField(max_length=250)),
                ('members_facebook_link', models.URLField()),
                ('members_twitter_link', models.URLField()),
                ('members_linkedin_link', models.URLField()),
                ('members_instagram_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='MiniService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miniservice_image', models.ImageField(upload_to='static/')),
                ('miniservice_title', models.CharField(max_length=250)),
                ('miniservice_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='static/')),
            ],
        ),
        migrations.CreateModel(
            name='Protect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protect_heading', models.CharField(max_length=250)),
                ('protect_details_main', models.TextField()),
                ('protect_image', models.ImageField(upload_to='static/')),
                ('protect_title', models.CharField(max_length=250)),
                ('protect_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SecondServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secondTitle', models.CharField(max_length=250)),
                ('secondParagraph', models.TextField()),
                ('secondImage', models.ImageField(upload_to='static/')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_heading', models.CharField(max_length=250)),
                ('services_image', models.ImageField(upload_to='static')),
                ('services_title', models.CharField(max_length=250)),
                ('services_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_title', models.CharField(max_length=25)),
                ('solution_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=250)),
                ('client_image', models.ImageField(upload_to='static/')),
                ('client_position', models.CharField(max_length=250)),
                ('client_review', models.TextField()),
                ('client_city', models.CharField(max_length=150)),
            ],
        ),
    ]
