# Generated by Django 5.1.3 on 2024-11-22 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Benefits',
        ),
        migrations.DeleteModel(
            name='Challenge',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Counter',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='Heading',
        ),
        migrations.DeleteModel(
            name='Members',
        ),
        migrations.DeleteModel(
            name='MiniService',
        ),
        migrations.DeleteModel(
            name='Partners',
        ),
        migrations.DeleteModel(
            name='Protect',
        ),
        migrations.DeleteModel(
            name='SecondServices',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='Solutions',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
