# Generated by Django 5.1.3 on 2024-11-23 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_benefits_benefits_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceshomepagemodel',
            name='service_title',
        ),
    ]
