# Generated by Django 5.1.3 on 2024-11-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_serviceshomepagemodel_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_tab_image', models.ImageField(upload_to='static/')),
                ('service_tab_heading', models.CharField(max_length=250)),
            ],
        ),
    ]
