# Generated by Django 5.1.3 on 2024-11-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_servicetab'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protect_title', models.CharField(max_length=250)),
                ('protect_details', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='protect',
            name='protect_details',
        ),
        migrations.RemoveField(
            model_name='protect',
            name='protect_image',
        ),
        migrations.RemoveField(
            model_name='protect',
            name='protect_title',
        ),
    ]
